#!/usr/bin/env python3
"""Scan docs/ for documents under each category and regenerate site metadata.

Generates four artifacts under docs/ from the same scan:
    - manifest.json   single source of truth for the landing pages
    - sitemap.xml     SEO: lists every public HTML page
    - robots.txt      SEO: crawl policy + sitemap pointer (allows AI/GEO bots)
    - llms.txt        GEO: llmstxt.org-style index for LLM crawlers

Structure expected:
    docs/<category>/<slug>/index.html

Title/description are extracted from the <title> tag and first <p class="lead"> or
<meta name="description">.
"""
from __future__ import annotations

import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
MANIFEST = DOCS / "manifest.json"
SITEMAP = DOCS / "sitemap.xml"
ROBOTS = DOCS / "robots.txt"
LLMS = DOCS / "llms.txt"

# Canonical site origin (matches docs/CNAME). No trailing slash.
SITE_URL = "https://ms.studydev.com"
SITE_TITLE = "SD Tech"
SITE_TAGLINE = "Microsoft 기술(Azure · Microsoft 365 · GitHub) 한국어 학습 자료 모음."
SITE_AUTHOR = "Hyounsoo Kim"

CATEGORIES = {
    "azure":  {"label": "Azure",         "description": "Azure Foundry, AI Agent, Cosmos DB, App Service 등 Azure 전반."},
    "m365":   {"label": "Microsoft 365", "description": "Copilot, Graph API, Teams, SharePoint 등."},
    "github": {"label": "GitHub",        "description": "GitHub Actions, Copilot, Codespaces 등."},
}

TITLE_RE = re.compile(r"<title>(.*?)</title>", re.IGNORECASE | re.DOTALL)
# Match content="..." or content='...' — the closing quote must match the opening one
# so values containing the other quote type aren't truncated.
DESC_META_RE = re.compile(
    r'<meta\s+name=["\']description["\']\s+content=(["\'])(.*?)\1',
    re.IGNORECASE | re.DOTALL,
)
LEAD_RE = re.compile(r'<p[^>]*class=["\'][^"\']*\blead\b[^"\']*["\'][^>]*>(.*?)</p>', re.IGNORECASE | re.DOTALL)
TAG_RE = re.compile(r"<[^>]+>")


def extract_meta(html: str) -> tuple[str, str]:
    title = ""
    desc = ""
    m = TITLE_RE.search(html)
    if m:
        title = TAG_RE.sub("", m.group(1)).strip()
    m = DESC_META_RE.search(html)
    if m:
        desc = m.group(2).strip()
    if not desc:
        m = LEAD_RE.search(html)
        if m:
            desc = TAG_RE.sub("", m.group(1)).strip()
            desc = re.sub(r"\s+", " ", desc)
            if len(desc) > 160:
                desc = desc[:157].rstrip() + "…"
    return title, desc


def scan_category(cat: str) -> list[dict]:
    cat_dir = DOCS / cat
    if not cat_dir.is_dir():
        return []
    docs: list[dict] = []
    for child in sorted(cat_dir.iterdir()):
        if not child.is_dir():
            continue
        index_html = child / "index.html"
        if not index_html.is_file():
            continue
        html = index_html.read_text(encoding="utf-8", errors="ignore")
        title, desc = extract_meta(html)
        docs.append({
            "slug": child.name,
            "title": title or child.name,
            "description": desc,
            "path": f"{cat}/{child.name}/",
        })
    return docs


def _url_for(html: Path) -> str:
    """Map a docs/ HTML file to its public URL path (index.html -> directory/)."""
    rel = html.relative_to(DOCS).as_posix()
    if rel == "index.html":
        return "/"
    if rel.endswith("/index.html"):
        return "/" + rel[: -len("index.html")]
    return "/" + rel


def _lastmod(html: Path) -> str:
    ts = datetime.fromtimestamp(html.stat().st_mtime, tz=timezone.utc)
    return ts.strftime("%Y-%m-%d")


def _xml_escape(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def list_pages() -> list[Path]:
    """Every public *.html under docs/ (excludes 404.html), sorted by URL."""
    return sorted(
        (p for p in DOCS.rglob("*.html") if p.name != "404.html"),
        key=_url_for,
    )


# --- SEO/GEO <head> injection -------------------------------------------------
SEO_START = "<!-- SEO:AUTO START (generated by scripts/generate_manifest.py) -->"
SEO_END = "<!-- SEO:AUTO END -->"
# Strip the whole block (incl. leading indent + trailing newline) before recomputing,
# so injection stays idempotent even for pages we added a <meta description> to.
SEO_BLOCK_RE = re.compile(
    r"[ \t]*" + re.escape(SEO_START) + r".*?" + re.escape(SEO_END) + r"\n?",
    re.DOTALL,
)
HEAD_CLOSE_RE = re.compile(r"</head>", re.IGNORECASE)
IMG_EXTS = {".png", ".jpg", ".jpeg", ".webp", ".gif"}

# HowTo is opt-in: a page declares it in <head> with author-controlled meta tags.
#   <meta name="seo:howto" content="HowTo 이름">
#   <meta name="seo:howto-step" content="단계 이름">   (2개 이상, 문서 순서대로)
# Optional "이름 :: 설명" splits into HowToStep name/text.
HOWTO_NAME_RE = re.compile(
    r'<meta\s+name=["\']seo:howto["\']\s+content=(["\'])(.*?)\1', re.IGNORECASE | re.DOTALL
)
HOWTO_STEP_RE = re.compile(
    r'<meta\s+name=["\']seo:howto-step["\']\s+content=(["\'])(.*?)\1', re.IGNORECASE | re.DOTALL
)


def _person_author() -> dict:
    return {"@type": "Person", "name": SITE_AUTHOR}


def _publisher() -> dict:
    return {"@type": "Organization", "name": SITE_TITLE, "url": SITE_URL + "/"}


def build_howto(base_html: str, abs_url: str, desc: str, date: str) -> dict | None:
    """Build an opt-in HowTo node from author-provided meta tags, else None."""
    name_m = HOWTO_NAME_RE.search(base_html)
    if not name_m:
        return None
    steps_raw = [m.group(2).strip() for m in HOWTO_STEP_RE.finditer(base_html)]
    steps_raw = [s for s in steps_raw if s]
    if len(steps_raw) < 2:
        return None
    steps = []
    for i, raw in enumerate(steps_raw, start=1):
        name, _, text = raw.partition("::")
        step = {"@type": "HowToStep", "position": i, "name": name.strip()}
        if text.strip():
            step["text"] = text.strip()
        steps.append(step)
    howto = {
        "@type": "HowTo",
        "name": name_m.group(2).strip(),
        "description": desc,
        "url": abs_url,
        "inLanguage": "ko-KR",
        "author": _person_author(),
        "publisher": _publisher(),
        "datePublished": date,
        "dateModified": date,
        "step": steps,
    }
    return howto


def _attr_escape(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace('"', "&quot;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _jsonld(obj: dict) -> str:
    """Serialize JSON-LD, escaping </ so the content can't break out of <script>."""
    return json.dumps(obj, ensure_ascii=False, indent=2).replace("</", "<\\/")


def _find_og_image(html_path: Path) -> str | None:
    img_dir = html_path.parent / "images"
    if img_dir.is_dir():
        for img in sorted(img_dir.iterdir()):
            if img.is_file() and img.suffix.lower() in IMG_EXTS:
                return SITE_URL + "/" + img.relative_to(DOCS).as_posix()
    return None


def _page_meta(html_path: Path, html: str) -> dict:
    """Resolve title/description/kind/category for a docs/ HTML page."""
    title, desc = extract_meta(html)
    parts = html_path.relative_to(DOCS).as_posix().split("/")
    if len(parts) == 1:                       # docs/index.html
        kind, cat = "home", None
        desc = desc or SITE_TAGLINE
        title = title or SITE_TITLE
    elif len(parts) == 2:                     # docs/<cat>/index.html
        kind, cat = "category", parts[0]
        desc = desc or CATEGORIES.get(cat, {}).get("description", "")
    else:                                     # docs/<cat>/<slug>/<file>.html
        kind, cat = "doc", parts[0]
    return {
        "title": title or html_path.stem,
        "desc": desc,
        "kind": kind,
        "cat": cat,
        "has_desc": bool(DESC_META_RE.search(html)),
    }


def build_seo_block(html_path: Path, html: str, date: str) -> str:
    """Build the canonical + Open Graph + Twitter + JSON-LD block for one page."""
    meta = _page_meta(html_path, html)
    title, desc, kind, cat = meta["title"], meta["desc"], meta["kind"], meta["cat"]
    abs_url = SITE_URL + _url_for(html_path)
    og_type = "article" if kind == "doc" else "website"
    og_image = _find_og_image(html_path)

    t, d = _attr_escape(title), _attr_escape(desc)
    twitter_card = "summary_large_image" if og_image else "summary"
    lines = [SEO_START]
    if not meta["has_desc"] and desc:
        lines.append(f'    <meta name="description" content="{d}">')
    lines += [
        f'    <link rel="canonical" href="{abs_url}">',
        f'    <meta property="og:type" content="{og_type}">',
        f'    <meta property="og:site_name" content="{SITE_TITLE}">',
        '    <meta property="og:locale" content="ko_KR">',
        f'    <meta property="og:title" content="{t}">',
        f'    <meta property="og:description" content="{d}">',
        f'    <meta property="og:url" content="{abs_url}">',
    ]
    if og_image:
        lines.append(f'    <meta property="og:image" content="{_attr_escape(og_image)}">')
    lines += [
        f'    <meta name="twitter:card" content="{twitter_card}">',
        f'    <meta name="twitter:title" content="{t}">',
        f'    <meta name="twitter:description" content="{d}">',
    ]
    if og_image:
        lines.append(f'    <meta name="twitter:image" content="{_attr_escape(og_image)}">')

    website = {"@type": "WebSite", "name": SITE_TITLE, "url": SITE_URL + "/"}
    crumbs = [{"@type": "ListItem", "position": 1, "name": "Home", "item": SITE_URL + "/"}]
    if cat:
        crumbs.append({
            "@type": "ListItem", "position": 2,
            "name": CATEGORIES.get(cat, {}).get("label", cat),
            "item": f"{SITE_URL}/{cat}/",
        })

    if kind == "home":
        graph = [{**website, "description": desc, "inLanguage": "ko-KR",
                  "author": _person_author(), "dateModified": date}]
    elif kind == "category":
        graph = [
            {"@type": "CollectionPage", "name": title, "description": desc,
             "url": abs_url, "inLanguage": "ko-KR", "isPartOf": website,
             "author": _person_author(), "dateModified": date},
            {"@type": "BreadcrumbList", "itemListElement": crumbs},
        ]
    else:  # doc
        article = {
            "@type": "TechArticle", "headline": title, "description": desc,
            "url": abs_url, "inLanguage": "ko-KR", "isPartOf": website,
            "author": _person_author(), "publisher": _publisher(),
            "datePublished": date, "dateModified": date,
        }
        if og_image:
            article["image"] = og_image
        crumbs.append({
            "@type": "ListItem", "position": len(crumbs) + 1,
            "name": title, "item": abs_url,
        })
        graph = [article, {"@type": "BreadcrumbList", "itemListElement": crumbs}]

    howto = build_howto(html, abs_url, desc, date)
    if howto:
        graph.append(howto)

    lines.append('    <script type="application/ld+json">')
    lines.append(_jsonld({"@context": "https://schema.org", "@graph": graph}))
    lines.append("    </script>")
    lines.append(SEO_END)
    return "\n".join(lines)


def inject_seo(pages: list[Path]) -> int:
    """Insert/replace the SEO block before </head> in each page. Returns #changed.

    The page's mtime is preserved across injection so that sitemap <lastmod> and
    the JSON-LD datePublished/dateModified stay pinned to the real content date
    (a genuine author edit still bumps mtime and thus the date).
    """
    changed = 0
    for page in pages:
        st = page.stat()
        date = datetime.fromtimestamp(st.st_mtime, tz=timezone.utc).strftime("%Y-%m-%d")
        html = page.read_text(encoding="utf-8", errors="ignore")
        # Recompute from the page with any previous block removed (idempotent).
        base = SEO_BLOCK_RE.sub("", html)
        block = build_seo_block(page, base, date)
        if not HEAD_CLOSE_RE.search(base):
            print(f"  ! no </head> in {page.relative_to(ROOT)}, skipped")
            continue
        new = HEAD_CLOSE_RE.sub(block + "\n</head>", base, count=1)
        if new != html:
            page.write_text(new, encoding="utf-8")
            os.utime(page, (st.st_atime, st.st_mtime))  # preserve content date
            changed += 1
    return changed


def write_sitemap() -> None:
    """Walk every public *.html under docs/ and emit a sitemap.xml."""
    pages = list_pages()
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ]
    for page in pages:
        loc = _xml_escape(SITE_URL + _url_for(page))
        lines.append("    <url>")
        lines.append(f"        <loc>{loc}</loc>")
        lines.append(f"        <lastmod>{_lastmod(page)}</lastmod>")
        lines.append("    </url>")
    lines.append("</urlset>")
    SITEMAP.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {SITEMAP.relative_to(ROOT)} ({len(pages)} urls)")


def write_robots() -> None:
    """Allow all crawlers (incl. AI/GEO bots) and point them to the sitemap."""
    content = (
        "# https://ms.studydev.com robots policy\n"
        "User-agent: *\n"
        "Allow: /\n\n"
        f"Sitemap: {SITE_URL}/sitemap.xml\n"
    )
    ROBOTS.write_text(content, encoding="utf-8")
    print(f"Wrote {ROBOTS.relative_to(ROOT)}")


def write_llms(manifest: dict) -> None:
    """Emit an llmstxt.org-style index so LLM crawlers can discover content (GEO)."""
    lines = [
        f"# {SITE_TITLE}",
        "",
        f"> {SITE_TAGLINE}",
        "",
        (
            "모든 문서는 한국어로 작성되며, 기술 용어는 영문을 그대로 사용합니다. "
            "각 항목은 Azure · Microsoft 365 · GitHub 세 카테고리로 분류됩니다."
        ),
        "",
    ]
    for cat, data in manifest["categories"].items():
        docs = data.get("docs", [])
        if not docs:
            continue
        lines.append(f"## {data['label']}")
        lines.append("")
        for doc in docs:
            url = f"{SITE_URL}/{doc['path']}"
            title = doc.get("title") or doc["slug"]
            desc = doc.get("description", "")
            entry = f"- [{title}]({url})"
            if desc:
                entry += f": {desc}"
            lines.append(entry)
        lines.append("")
    LLMS.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {LLMS.relative_to(ROOT)}")


def build_manifest() -> dict:
    manifest = {
        "generatedAt": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "categories": {},
    }
    for cat, meta in CATEGORIES.items():
        manifest["categories"][cat] = {
            "label": meta["label"],
            "description": meta["description"],
            "docs": scan_category(cat),
        }
    return manifest


def main() -> None:
    manifest = build_manifest()
    MANIFEST.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=4) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {MANIFEST.relative_to(ROOT)}")
    changed = inject_seo(list_pages())
    print(f"Injected SEO/GEO head block ({changed} page(s) updated)")
    write_sitemap()
    write_robots()
    write_llms(manifest)


if __name__ == "__main__":
    main()
